export const ADLCareTask = [
  {
    ADLCategory: "Dressing",
    AssessmentTrackingId: 156,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-16",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  },
  {
    ADLCategory: "Grooming",
    AssessmentTrackingId: 157,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-33",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  },
  {
    ADLCategory: "Meals",
    AssessmentTrackingId: 158,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-28",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  },
  {
    ADLCategory: "Psychosocial",
    AssessmentTrackingId: 159,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-56",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  },
  {
    ADLCategory: "StatusChecks",
    AssessmentTrackingId: 160,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-53",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  },
  {
    ADLCategory: "Toileting",
    AssessmentTrackingId: 161,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-22",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  },
  {
    ADLCategory: "Transfers",
    AssessmentTrackingId: 162,
    CompletedDate: null,
    FollowUpDate: null,
    InitialBy: null,
    IsCompleted: false,
    LevelDescription: null,
    Points: null,
    ReasonForReassess: null,
    Shift: "ALL",
    SignedBy: null,
    TaskDate: "2019-09-30T14:12:48.76",
    TaskName: "ADL-5",
    TaskNotes: null,
    TaskStatus: null,
    TaskStatusNotes: null,
    TrackDate: "2019-09-30T00:00:00"
  }
];
