export const ADLCareLevels = [
  {
    AdlCategory: "Transfers",
    AdlCategoryId: 13,
    AdlCategoryType: "Transfers",
    AdlId: 5,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsSun: 0,
    PointsMon: 0,
    PointsTue: 0,
    PointsWed: 0,
    PointsThu: 0,
    PointsFri: 0,
    PointsSat: 0,
    PointsTotal: 0,
    PointsExtra: 0
  },
  {
    AdlCategory: "Toileting",
    AdlCategoryId: 12,
    AdlCategoryType: "Toileting",
    AdlId: 22,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "StatusChecks",
    AdlCategoryId: 11,
    AdlCategoryType: "StatusChecks",
    AdlId: 53,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "SpecialCare",
    AdlCategoryId: 10,
    AdlCategoryType: "SpecialCare",
    AdlId: -1,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Psychosocial",
    AdlCategoryId: 9,
    AdlCategoryType: "Psychosocial",
    AdlId: 56,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "MedAssist",
    AdlCategoryId: 8,
    AdlCategoryType: "MedAssist",
    AdlId: 0,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 100,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Meals",
    AdlCategoryId: 7,
    AdlCategoryType: "Meals",
    AdlId: 28,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Laundry",
    AdlCategoryId: 6,
    AdlCategoryType: "Laundry",
    AdlId: 39,
    EnableAM: false,
    EnableDaily: true,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Grooming",
    AdlCategoryId: 5,
    AdlCategoryType: "Grooming",
    AdlId: 33,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Dressing",
    AdlCategoryId: 4,
    AdlCategoryType: "Dressing",
    AdlId: 16,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Bathing",
    AdlCategoryId: 3,
    AdlCategoryType: "Bathing",
    AdlId: 10,
    EnableAM: false,
    EnableDaily: true,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  },
  {
    AdlCategory: "Ambulation",
    AdlCategoryId: 2,
    AdlCategoryType: "Ambulation",
    AdlId: 0,
    EnableAM: false,
    EnableDaily: false,
    EnableNOC: false,
    EnablePM: false,
    PointsBase: 0,
    PointsDaily: 0,
    PointsExtra: 0,
    PointsFri: 0,
    PointsMon: 0,
    PointsSat: 0,
    PointsSun: 0,
    PointsThu: 0,
    PointsTotal: 0,
    PointsTue: 0,
    PointsWed: 0
  }
];
