export const AssessmentTask = [
  {
    ADLId: 1,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 1,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Ambulates independently with or without an assistive device",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-1"
  },
  {
    ADLId: 10,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 10,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Bathes Independently",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-10"
  },
  {
    ADLId: 11,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 11,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires reminders only",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-11"
  },
  {
    ADLId: 12,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 12,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires items prepared",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-12"
  },
  {
    ADLId: 13,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 13,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires Stand-By assistance ",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-13"
  },
  {
    ADLId: 14,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 14,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 1 Person Total assistance",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-14"
  },
  {
    ADLId: 15,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 15,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 2 Person assistance  and additional time",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-15"
  },
  {
    ADLId: 16,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 16,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-16"
  },
  {
    ADLId: 17,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 17,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires reminders to dress appropriately",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-17"
  },
  {
    ADLId: 18,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 18,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires clothing to be set out or removed from room",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-18"
  },
  {
    ADLId: 19,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 19,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires stand-by assistance with dressing",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-19"
  },
  {
    ADLId: 2,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 2,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires stand-by assistance of one person when ambulating",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-2"
  },
  {
    ADLId: 20,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 20,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 1 person total assistance with dressing",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-20"
  },
  {
    ADLId: 21,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 21,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Requires 2 person total assistance with dressing and additional time",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-21"
  },
  {
    ADLId: 22,
    AssessmentCategoryId: 12,
    AssessmentTaskId: 22,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent with toileting",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-22"
  },
  {
    ADLId: 23,
    AssessmentCategoryId: 12,
    AssessmentTaskId: 23,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires verbal reminders to use the toilet",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-23"
  },
  {
    ADLId: 24,
    AssessmentCategoryId: 12,
    AssessmentTaskId: 24,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires cueing while toileting",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-24"
  },
  {
    ADLId: 25,
    AssessmentCategoryId: 12,
    AssessmentTaskId: 25,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires stand-by assistance while toileting",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-25"
  },
  {
    ADLId: 26,
    AssessmentCategoryId: 12,
    AssessmentTaskId: 26,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 1 person total assistance with toileting",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-26"
  },
  {
    ADLId: 27,
    AssessmentCategoryId: 12,
    AssessmentTaskId: 27,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 2 person total assistance and additional time",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-27"
  },
  {
    ADLId: 28,
    AssessmentCategoryId: 7,
    AssessmentTaskId: 28,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-28"
  },
  {
    ADLId: 29,
    AssessmentCategoryId: 7,
    AssessmentTaskId: 29,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires adaptive equipment",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-29"
  },
  {
    ADLId: 3,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 3,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Requires 1 person total assist or wheelchair escort to and from activities, meals, etc.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-3"
  },
  {
    ADLId: 30,
    AssessmentCategoryId: 7,
    AssessmentTaskId: 30,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires food cut, chopped, pureed, or otherwise prepared ",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-30"
  },
  {
    ADLId: 31,
    AssessmentCategoryId: 7,
    AssessmentTaskId: 31,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires prompting throughout meals",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-31"
  },
  {
    ADLId: 32,
    AssessmentCategoryId: 7,
    AssessmentTaskId: 32,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires total assistance",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-32"
  },
  {
    ADLId: 33,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 33,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-33"
  },
  {
    ADLId: 34,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 34,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires reminders to groom appropriately",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-34"
  },
  {
    ADLId: 35,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 35,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires preparation of grooming items",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-35"
  },
  {
    ADLId: 36,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 36,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires stand-by assistance with grooming",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-36"
  },
  {
    ADLId: 37,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 37,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 1 person total assistance with grooming",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-37"
  },
  {
    ADLId: 38,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 38,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Requires 2 person total assistance with grooming and additional time",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-38"
  },
  {
    ADLId: 39,
    AssessmentCategoryId: 6,
    AssessmentTaskId: 39,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-39"
  },
  {
    ADLId: 4,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 4,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Requires 2 person total assistance while ambulating / escorting and additional time",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-4"
  },
  {
    ADLId: 40,
    AssessmentCategoryId: 6,
    AssessmentTaskId: 40,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Staff",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-40"
  },
  {
    ADLId: 41,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 41,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Oxygen",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-41"
  },
  {
    ADLId: 42,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 42,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Ostomy",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-42"
  },
  {
    ADLId: 43,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 43,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Hospice Care",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-43"
  },
  {
    ADLId: 44,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 44,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Catheter",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-44"
  },
  {
    ADLId: 45,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 45,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Complex Wound/Skin Care",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-45"
  },
  {
    ADLId: 46,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 46,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Diabetic",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-46"
  },
  {
    ADLId: 47,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 47,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Fall Concern",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-47"
  },
  {
    ADLId: 48,
    AssessmentCategoryId: 1,
    AssessmentTaskId: 48,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Adjust Points Assessed: ",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-48"
  },
  {
    ADLId: 49,
    AssessmentCategoryId: 8,
    AssessmentTaskId: 49,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-49"
  },
  {
    ADLId: 5,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 5,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-5"
  },
  {
    ADLId: 50,
    AssessmentCategoryId: 8,
    AssessmentTaskId: 50,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Requires assistance with the self-administration of medications",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-50"
  },
  {
    ADLId: 53,
    AssessmentCategoryId: 11,
    AssessmentTaskId: 53,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "No additional status checks",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-53"
  },
  {
    ADLId: 54,
    AssessmentCategoryId: 11,
    AssessmentTaskId: 54,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "4 per shift",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-54"
  },
  {
    ADLId: 55,
    AssessmentCategoryId: 11,
    AssessmentTaskId: 55,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "8 per shift",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-55"
  },
  {
    ADLId: 56,
    AssessmentCategoryId: 9,
    AssessmentTaskId: 56,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Independent",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-56"
  },
  {
    ADLId: 57,
    AssessmentCategoryId: 9,
    AssessmentTaskId: 57,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Minimal - prompting, cueing, reminding",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-57"
  },
  {
    ADLId: 58,
    AssessmentCategoryId: 9,
    AssessmentTaskId: 58,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Moderate - requires redirection, repetitive interventions, room visits",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-58"
  },
  {
    ADLId: 59,
    AssessmentCategoryId: 9,
    AssessmentTaskId: 59,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Extensive - multiple behavioral interventions",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-59"
  },
  {
    ADLId: 6,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 6,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires reminders",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-6"
  },
  {
    ADLId: 60,
    AssessmentCategoryId: 11,
    AssessmentTaskId: 60,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "16 per shift",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-60"
  },
  {
    ADLId: 61,
    AssessmentCategoryId: 10,
    AssessmentTaskId: 61,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Lab Monitoring",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-61"
  },
  {
    ADLId: 62,
    AssessmentCategoryId: 6,
    AssessmentTaskId: 62,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Family",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-62"
  },
  {
    ADLId: 63,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 63,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires occasional assistance or wheelchair escort",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-63"
  },
  {
    ADLId: 64,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 64,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Walks and climbs and descends stairs with constant supervision and/or assistance.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-64"
  },
  {
    ADLId: 65,
    AssessmentCategoryId: 2,
    AssessmentTaskId: 65,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Chairfast or bedfast. Requires total assistance for mobility.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-65"
  },
  {
    ADLId: 66,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 66,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Intermittent Assistance: Transfers with minimal human assistance and/or supervision.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-66"
  },
  {
    ADLId: 68,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 68,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Total Assistance: Chairfast or bedfast, unable to transfer, pivot, bear weight or turn self in bed.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-68"
  },
  {
    ADLId: 69,
    AssessmentCategoryId: 3,
    AssessmentTaskId: 69,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Total Assistance: Unable to use shower or tub. Bathed in bed or at bedside.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-69"
  },
  {
    ADLId: 7,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 7,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires stand-by assistance",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-7"
  },
  {
    ADLId: 70,
    AssessmentCategoryId: 4,
    AssessmentTaskId: 70,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Total Assistance: Requires another person to dress and undress upper and lower body.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-70"
  },
  {
    ADLId: 71,
    AssessmentCategoryId: 5,
    AssessmentTaskId: 71,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Total Assistance: Depends entirely upon someone else for grooming.",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-71"
  },
  {
    ADLId: 72,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 72,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description:
      "Continual Assistance: Unable to transfer but can bear weight and pivot with 1 person assist",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-72"
  },
  {
    ADLId: 8,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 8,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 1 person total assistance",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-8"
  },
  {
    ADLId: 9,
    AssessmentCategoryId: 13,
    AssessmentTaskId: 9,
    CreatedBy: null,
    CreatedDate: "2019-09-29T13:49:17.47",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "Requires 2 person total assistance and additional time",
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-29T13:49:17.47",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ADL-9"
  }
];
