export const AssessmentShift = [
  {
    AssessmentShiftId: 4,
    CreatedBy: null,
    CreatedDate: "2019-09-27T01:44:58.963",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "ALL",
    EndTime: null,
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-27T01:44:58.963",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "ALL",
    StartTime: null
  },
  {
    AssessmentShiftId: 1,
    CreatedBy: null,
    CreatedDate: "2019-09-09T16:21:30.16",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "AM",
    EndTime: null,
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-09T16:21:30.16",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "AM",
    StartTime: null
  },
  {
    AssessmentShiftId: 3,
    CreatedBy: null,
    CreatedDate: "2019-09-09T16:21:30.17",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "NOC",
    EndTime: null,
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-09T16:21:30.17",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "NOC",
    StartTime: null
  },
  {
    AssessmentShiftId: 2,
    CreatedBy: null,
    CreatedDate: "2019-09-09T16:21:30.167",
    CreatedLoginBy: "AdvantageAdmin",
    CreatedStation: "DEVPEGGY",
    Description: "PM",
    EndTime: null,
    IsActive: true,
    ModifiedBy: null,
    ModifiedDate: "2019-09-09T16:21:30.167",
    ModifiedLoginBy: "AdvantageAdmin",
    ModifiedStation: "DEVPEGGY",
    Name: "PM",
    StartTime: null
  }
];
